links:
  home: "home"
  help: "help"
  login: "#"
  rails:
    url: "https://www.railstutorial.org"
    book: "https://www.railstutorial.org/book"
    help: "https://www.railstutorial.org/help"
user:
  name:
    max_length: 50
  email:
    max_length: 255
    regex_valid: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
page: 10
gravatar:
  md: 80
  size: 50
  link: "http://gravatar.com/emails"
